//
// Created by ASUS on 2/5/2020.
//

#ifndef COUNT_INVERSIONS_RECURSIVE_COUNT_INVERSIONS_RECURSIVE_H
#define COUNT_INVERSIONS_RECURSIVE_COUNT_INVERSIONS_RECURSIVE_H


class count_inversions_recursive {

};


#endif //COUNT_INVERSIONS_RECURSIVE_COUNT_INVERSIONS_RECURSIVE_H
